-- ============================================================
-- ATLANTIS MC — TEK SUPABASE ŞEMASI
-- Mevcut schema + yeni profil/sohbet özellikleri birleştirilmiştir.
-- SQL Editor'da tek parça olarak çalıştırılmak üzere hazırlanmıştır.
-- ============================================================

-- Atlantis MC — hesap, chat, rol ve moderasyon şeması
-- Supabase SQL Editor'da tek seferde çalıştırılabilir.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  site_role text not null default 'user',
  muted_until timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint username_format check (
    username is null or username ~ '^[A-Za-zÇĞİÖŞÜçğıöşü][A-Za-zÇĞİÖŞÜçğıöşü0-9]{2,15}$'
  ),
  constraint site_role_format check (site_role in ('user','moderator','admin'))
);

create unique index if not exists profiles_username_lower_idx on public.profiles(lower(username)) where username is not null;

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  message text not null check (char_length(message) between 1 and 300),
  created_at timestamptz not null default now()
);

create index if not exists messages_created_at_idx on public.messages(created_at desc);
create index if not exists messages_user_created_idx on public.messages(user_id,created_at desc);

alter table public.profiles enable row level security;
alter table public.messages enable row level security;

-- Kullanıcıların yalnızca gerekli verileri okuyabilmesi.
drop policy if exists "profiles readable" on public.profiles;
create policy "profiles readable" on public.profiles
for select using (true);

-- Profilleri normal istemciden doğrudan değiştirmiyoruz; aşağıdaki RPC'ler kullanılıyor.
drop policy if exists "users insert own profile" on public.profiles;
drop policy if exists "users update own profile" on public.profiles;

-- Mesajları herkes okuyabilir; gönderim yalnızca RPC ile yapılır.
drop policy if exists "messages readable" on public.messages;
create policy "messages readable" on public.messages
for select using (true);

drop policy if exists "authenticated send messages" on public.messages;

-- Kullanıcı kendi mesajını silebilir (istersen moderasyon panelinden de silebiliriz).
drop policy if exists "own messages delete" on public.messages;
create policy "own messages delete" on public.messages
for delete using (auth.uid() = user_id);

-- Rol kontrolü için güvenli yardımcı fonksiyon.
create or replace function public.has_site_role(required_role text)
returns boolean
language plpgsql
security definer
set search_path = public
stable
as $$
declare
  current_role text;
begin
  select site_role into current_role from public.profiles where id = auth.uid();
  if current_role = 'admin' then return true; end if;
  if required_role = 'admin' then return false; end if;
  return current_role = 'moderator';
end;
$$;

revoke all on function public.has_site_role(text) from public;
grant execute on function public.has_site_role(text) to authenticated;

-- Kendi kullanıcı adını ayarlama.
create or replace function public.set_my_username(new_username text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  clean text := btrim(new_username);
  taken boolean;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  if clean !~ '^[A-Za-zÇĞİÖŞÜçğıöşü][A-Za-zÇĞİÖŞÜçğıöşü0-9]{2,15}$' then
    raise exception 'invalid username';
  end if;
  select exists(select 1 from public.profiles where lower(username)=lower(clean) and id <> auth.uid()) into taken;
  if taken then raise exception 'username taken'; end if;
  insert into public.profiles(id,username,updated_at)
  values(auth.uid(),clean,now())
  on conflict (id) do update set username=excluded.username,updated_at=now();
  return true;
end;
$$;

revoke all on function public.set_my_username(text) from public;
grant execute on function public.set_my_username(text) to authenticated;

-- Chat gönderimi: 300 karakter ve kullanıcı başına 3 saniyelik sunucu tarafı sınırı.
create or replace function public.send_chat_message(p_message text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  clean text := btrim(p_message);
  p record;
  last_time timestamptz;
begin
  if auth.uid() is null then raise exception 'Giriş yapmalısın.'; end if;
  if char_length(clean) < 1 or char_length(clean) > 300 then raise exception 'Mesaj 1-300 karakter olmalı.'; end if;

  select username,site_role,muted_until into p from public.profiles where id=auth.uid();
  if p.username is null then raise exception 'Önce kullanıcı adını belirlemelisin.'; end if;
  if p.muted_until is not null and p.muted_until > now() then raise exception 'Sohbet kullanımın geçici olarak kısıtlandı.'; end if;

  select created_at into last_time
  from public.messages
  where user_id=auth.uid()
  order by created_at desc
  limit 1;

  if last_time is not null and last_time > now() - interval '3 seconds' then
    raise exception 'Yeni mesaj göndermek için biraz bekle.';
  end if;

  insert into public.messages(user_id,username,message)
  values(auth.uid(),p.username,clean);

  return jsonb_build_object('ok',true,'muted_until',null);
end;
$$;

revoke all on function public.send_chat_message(text) from public;
grant execute on function public.send_chat_message(text) to authenticated;

-- Moderatör/admin mesaj silebilir.
create or replace function public.moderation_delete_message(target_message_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.has_site_role('moderator') then raise exception 'no permission'; end if;
  delete from public.messages where id=target_message_id;
  return true;
end;
$$;

revoke all on function public.moderation_delete_message(bigint) from public;
grant execute on function public.moderation_delete_message(bigint) to authenticated;

-- Moderatör/admin kullanıcıyı susturabilir. Süre saniye cinsindedir.
create or replace function public.moderation_set_mute(target_user_id uuid, duration_seconds integer)
returns timestamptz
language plpgsql
security definer
set search_path = public
as $$
declare
  target_role text;
  until_time timestamptz;
begin
  if not public.has_site_role('moderator') then raise exception 'no permission'; end if;
  select site_role into target_role from public.profiles where id=target_user_id;
  if target_role = 'admin' and (select site_role from public.profiles where id=auth.uid()) <> 'admin' then
    raise exception 'cannot mute admin';
  end if;
  if duration_seconds <= 0 then until_time := null; else until_time := now() + make_interval(secs => duration_seconds); end if;
  update public.profiles set muted_until=until_time,updated_at=now() where id=target_user_id;
  return until_time;
end;
$$;

revoke all on function public.moderation_set_mute(uuid,integer) from public;
grant execute on function public.moderation_set_mute(uuid,integer) to authenticated;

-- Sadece admin rol verebilir: user / moderator / admin.
create or replace function public.admin_set_role(target_user_id uuid, new_role text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  own_role text;
begin
  select site_role into own_role from public.profiles where id=auth.uid();
  if own_role <> 'admin' then raise exception 'no permission'; end if;
  if new_role not in ('user','moderator','admin') then raise exception 'invalid role'; end if;
  update public.profiles set site_role=new_role,updated_at=now() where id=target_user_id;
  return true;
end;
$$;

revoke all on function public.admin_set_role(uuid,text) from public;
grant execute on function public.admin_set_role(uuid,text) to authenticated;

-- Yeni Auth kullanıcısı için profil satırı oluştur.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles(id,username)
  values(new.id,null)
  on conflict (id) do nothing;
  if (new.raw_user_meta_data ? 'username') then
    update public.profiles
    set username = new.raw_user_meta_data->>'username', updated_at=now()
    where id=new.id;
  end if;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Realtime: messages tablosu.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='messages'
  ) then
    alter publication supabase_realtime add table public.messages;
  end if;
exception when undefined_object then
  null;
end $$;

-- ============================================================
-- Atlantis MC — profil + gelişmiş sohbet yükseltmesi
-- Bu bölüm, yukarıdaki mevcut şemanın devamıdır.
-- ============================================================

begin;

-- Profil alanları
alter table public.profiles
  add column if not exists bio text not null default '',
  add column if not exists avatar_url text,
  add column if not exists last_seen timestamptz;

-- Mesaj alanları
alter table public.messages
  add column if not exists edited_at timestamptz,
  add column if not exists avatar_url text;

-- Kullanıcı profilini okuyabilir; sahibi kendi bio/avatar/last_seen
-- gibi alanlarını güncelleyebilir.
drop policy if exists "profiles readable" on public.profiles;
drop policy if exists "profiles_public_read" on public.profiles;
create policy "profiles readable" on public.profiles
for select to anon, authenticated
using (true);

drop policy if exists "profiles_owner_update" on public.profiles;
drop policy if exists "users update own profile" on public.profiles;
create policy "profiles_owner_update" on public.profiles
for update to authenticated
using (id = auth.uid())
with check (id = auth.uid());

-- Mesajlar okunabilir.
drop policy if exists "messages readable" on public.messages;
drop policy if exists "messages_auth_select" on public.messages;
create policy "messages readable" on public.messages
for select to authenticated
using (true);

-- Kullanıcı sadece kendi mesajını düzenleyebilir/silebilir.
drop policy if exists "messages_owner_update" on public.messages;
create policy "messages_owner_update" on public.messages
for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "own messages delete" on public.messages;
drop policy if exists "messages_owner_delete" on public.messages;
create policy "own messages delete" on public.messages
for delete to authenticated
using (user_id = auth.uid());

-- Son görülme güncelleme RPC'si
create or replace function public.touch_my_last_seen()
returns void
language sql
security invoker
set search_path = public
as $$
  update public.profiles
     set last_seen = now(),
         updated_at = now()
   where id = auth.uid();
$$;

revoke all on function public.touch_my_last_seen() from public;
grant execute on function public.touch_my_last_seen() to authenticated;

-- Realtime: messages tablosunun publication içinde olduğundan emin ol.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='messages'
  ) then
    execute 'alter publication supabase_realtime add table public.messages';
  end if;
exception when undefined_object then
  null;
end $$;

commit;
